package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.DocRouter;
import com.lxh.mybatis.entity.DocRouterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocRouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int countByExample(DocRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int deleteByExample(DocRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int insert(DocRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int insertSelective(DocRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    List<DocRouter> selectByExample(DocRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    DocRouter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DocRouter record, @Param("example") DocRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DocRouter record, @Param("example") DocRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DocRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DocRouter record);
}