package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.hospRouterRelation;
import com.lxh.mybatis.entity.hospRouterRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hospRouterRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int countByExample(hospRouterRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int deleteByExample(hospRouterRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("ancestor") Integer ancestor, @Param("descendant") Integer descendant);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int insert(hospRouterRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int insertSelective(hospRouterRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    List<hospRouterRelation> selectByExample(hospRouterRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    hospRouterRelation selectByPrimaryKey(@Param("ancestor") Integer ancestor, @Param("descendant") Integer descendant);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hospRouterRelation record, @Param("example") hospRouterRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hospRouterRelation record, @Param("example") hospRouterRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hospRouterRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router_relation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hospRouterRelation record);
}