package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.hospRouter;
import com.lxh.mybatis.entity.hospRouterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hospRouterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int countByExample(hospRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int deleteByExample(hospRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int insert(hospRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int insertSelective(hospRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    List<hospRouter> selectByExample(hospRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    hospRouter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hospRouter record, @Param("example") hospRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hospRouter record, @Param("example") hospRouterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hospRouter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_router
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hospRouter record);
}