package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.hospSet;
import com.lxh.mybatis.entity.hospExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hospMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int countByExample(hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int deleteByExample(hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int insert(hospSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int insertSelective(hospSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    List<hospSet> selectByExample(hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    hospSet selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hospSet record, @Param("example") hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hospSet record, @Param("example") hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hospSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hospSet record);
}