package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.hospPriv;
import com.lxh.mybatis.entity.hospPrivExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hospPrivMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int countByExample(hospPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int deleteByExample(hospPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("hospId") Integer hospId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int insert(hospPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int insertSelective(hospPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    List<hospPriv> selectByExample(hospPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    hospPriv selectByPrimaryKey(@Param("id") Integer id, @Param("hospId") Integer hospId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hospPriv record, @Param("example") hospPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hospPriv record, @Param("example") hospPrivExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hospPriv record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_priv
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hospPriv record);
}