package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.hospSection;
import com.lxh.mybatis.entity.hospSectionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hospSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int countByExample(hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int deleteByExample(hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int insert(hospSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int insertSelective(hospSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    List<hospSection> selectByExample(hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    hospSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hospSection record, @Param("example") hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hospSection record, @Param("example") hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hospSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hospSection record);
}