package com.lxh.mybatis.mapper;

import com.lxh.mybatis.entity.hosp;
import com.lxh.mybatis.entity.hospExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface hospMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int countByExample(hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int deleteByExample(hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int insert(hosp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int insertSelective(hosp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    List<hosp> selectByExample(hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    hosp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hosp record, @Param("example") hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hosp record, @Param("example") hospExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hosp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_set
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hosp record);
}