/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CascadeTree: typeof import('./src/components/cascadeTree/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Menu: typeof import('./src/components/menu/menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/assembly/tableAssembly/Table.vue')['default']
    Title: typeof import('./src/components/assembly/pageTopTitle/Title.vue')['default']
    UnpluginDialog: typeof import('./src/components/unplugin-dialog.vue')['default']
  }
}

// For TSX support
declare global {
  const CascadeTree: typeof import('./src/components/cascadeTree/index.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const Menu: typeof import('./src/components/menu/menu.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Table: typeof import('./src/components/assembly/tableAssembly/Table.vue')['default']
  const Title: typeof import('./src/components/assembly/pageTopTitle/Title.vue')['default']
  const UnpluginDialog: typeof import('./src/components/unplugin-dialog.vue')['default']
}