package com.lxh.admin.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.lxh.admin.entity.DocContent;
import com.lxh.admin.entity.DocContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocContentMapper extends BaseMapper<DocContent> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    long countByExample(DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int deleteByExample(DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int insert(DocContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int insertSelective(DocContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    List<DocContent> selectByExampleWithBLOBs(DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    List<DocContent> selectByExample(DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    DocContent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") DocContent row, @Param("example") DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") DocContent row, @Param("example") DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") DocContent row, @Param("example") DocContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DocContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DocContent row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_content
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DocContent row);
}