package com.lxh.admin.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.lxh.admin.entity.Doc;
import com.lxh.admin.entity.DocExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocMapper extends BaseMapper<Doc> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    long countByExample(DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int deleteByExample(DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int insert(Doc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int insertSelective(Doc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    List<Doc> selectByExample(DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    Doc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Doc row, @Param("example") DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Doc row, @Param("example") DocExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Doc row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Doc row);
}