package com.lxh.admin.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.lxh.joint.Section;
import com.lxh.mybatis.entity.hospSection;
import com.lxh.mybatis.entity.hospSectionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface hospSectionMapper extends BaseMapper<hospSection> {
    @Select("select * from hosp_section a left join hosp_section_relation b on a.id = b.descendant")
    List<Section> getSection();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int countByExample(hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int deleteByExample(hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int insert(hospSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int insertSelective(hospSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    List<hospSection> selectByExample(hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    hospSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") hospSection record, @Param("example") hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") hospSection record, @Param("example") hospSectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(hospSection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hosp_section
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(hospSection record);
}