package com.lxh.mybatis.entity;

public class hospSectionRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_section_relation.ancestor
     *
     * @mbggenerated
     */
    private Integer ancestor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_section_relation.descendant
     *
     * @mbggenerated
     */
    private Integer descendant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_section_relation.distance
     *
     * @mbggenerated
     */
    private Integer distance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_section_relation.ancestor
     *
     * @return the value of hosp_section_relation.ancestor
     *
     * @mbggenerated
     */
    public Integer getAncestor() {
        return ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_section_relation.ancestor
     *
     * @param ancestor the value for hosp_section_relation.ancestor
     *
     * @mbggenerated
     */
    public void setAncestor(Integer ancestor) {
        this.ancestor = ancestor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_section_relation.descendant
     *
     * @return the value of hosp_section_relation.descendant
     *
     * @mbggenerated
     */
    public Integer getDescendant() {
        return descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_section_relation.descendant
     *
     * @param descendant the value for hosp_section_relation.descendant
     *
     * @mbggenerated
     */
    public void setDescendant(Integer descendant) {
        this.descendant = descendant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_section_relation.distance
     *
     * @return the value of hosp_section_relation.distance
     *
     * @mbggenerated
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_section_relation.distance
     *
     * @param distance the value for hosp_section_relation.distance
     *
     * @mbggenerated
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
}