package com.lxh.mybatis.entity;

public class hospUserInfo {
    @Override
    public String toString() {
        return "hospUserInfo{" +
                "id=" + id +
                ", uid=" + uid +
                ", headerImage='" + headerImage + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_user_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_user_info.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_user_info.header_image
     *
     * @mbggenerated
     */
    private String headerImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_user_info.id
     *
     * @return the value of hosp_user_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_user_info.id
     *
     * @param id the value for hosp_user_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_user_info.uid
     *
     * @return the value of hosp_user_info.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_user_info.uid
     *
     * @param uid the value for hosp_user_info.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_user_info.header_image
     *
     * @return the value of hosp_user_info.header_image
     *
     * @mbggenerated
     */
    public String getHeaderImage() {
        return headerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_user_info.header_image
     *
     * @param headerImage the value for hosp_user_info.header_image
     *
     * @mbggenerated
     */
    public void setHeaderImage(String headerImage) {
        this.headerImage = headerImage == null ? null : headerImage.trim();
    }
}