package com.lxh.mybatis.entity;

public class hospSection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_section.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hosp_section.section_name
     *
     * @mbggenerated
     */
    private String sectionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_section.id
     *
     * @return the value of hosp_section.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_section.id
     *
     * @param id the value for hosp_section.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hosp_section.section_name
     *
     * @return the value of hosp_section.section_name
     *
     * @mbggenerated
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hosp_section.section_name
     *
     * @param sectionName the value for hosp_section.section_name
     *
     * @mbggenerated
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }
}